version: 2
jobs:
  setup_and_run:
    macos:
      xcode: "10.1.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: pip install requests
      - run: git clone https://grahamgilbert:${github_api}@github.com/grahamgilbert/macaduck19-munki_repo.git
      - run: curl -OL https://github.com/autopkg/autopkg/releases/download/v1.0.4/autopkg-1.0.4.pkg
      - run: installer -pkg autopkg-1.0.4.pkg -target /
      - run: mkdir -p ${HOME}/AutoPkg
      - run: ln -s recipe_repos ${HOME}/AutoPkg/RecipeRepos
      - run: ln -s recipe_overrides ${HOME}/AutoPkg/RecipeOverrides

workflows:
  version: 2
  commit:
    jobs:
      - setup_and_run

  schedule:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - setup_and_run