version: 2
jobs:
  setup_and_run:
    macos:
      xcode: "10.1.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: pip install requests
      - run: git clone https://grahamgilbert:${github_api}@github.com/grahamgilbert/macaduck19-munki_repo.git ${CIRCLE_WORKING_DIRECTORY}/macaduck19-munki_repo
      - run: curl -OL https://github.com/autopkg/autopkg/releases/download/v1.0.4/autopkg-1.0.4.pkg
      - run: sudo installer -pkg autopkg-1.0.4.pkg -target /
      - run: mkdir -p ${HOME}/Library/AutoPkg
      - run: ln -s recipe_repos ${HOME}/Library/AutoPkg/RecipeRepos
      - run: ln -s recipe_overrides ${HOME}/Library/AutoPkg/RecipeOverrides
      - run: python runner.py

workflows:
  version: 2
  commit:
    jobs:
      - setup_and_run

  schedule:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - setup_and_run