version: 2
jobs:
  setup_and_run:
    macos:
      xcode: "10.1.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: pip install requests
      - run: git clone https://grahamgilbert:${github_api}@github.com/grahamgilbert/macaduck19-munki_repo.git ${HOME}/macaduck19-munki_repo
      - run: curl -OL https://github.com/autopkg/autopkg/releases/download/v1.0.4/autopkg-1.0.4.pkg
      - run: sudo installer -pkg autopkg-1.0.4.pkg -target /
      - run: mkdir -p ~/Library/AutoPkg
      - run: cp -r recipe_repos ~/Library/AutoPkg/RecipeRepos
      - run: cp -r recipe_overrides ~/Library/AutoPkg/RecipeOverrides
      - run: cp com.github.autopkg.plist ~/Library/Preferences/com.github.autopkg.plist
      - run: python runner.py

workflows:
  version: 2
  commit:
    jobs:
      - setup_and_run

  schedule:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - setup_and_run